name: Test Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  verify:
    name: verify / python-${{ matrix.python-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Create hello.txt
        shell: bash -l {0}
        run: |
          mkdir -p /tmp/matchms/_build
          touch /tmp/matchms/_build/hello.txt

      - name: Upload package artifact from build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v1
        with:
          name: test-artifact
          path: /tmp/matchms/_build

      - name: Download conda package from build job for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/download-artifact@v1
        with:
          name: test-artifact
          path: "%TEMP%\\matchms\\_build"

      - name: Show variables for Windows-1
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          echo "cmd-1"
          export BUILD_FOLDER="%TEMP%\matchms\_build\"
          echo "cmd-2"
          echo ${BUILD_FOLDER}
          echo "cmd-3"
          echo file:\\${BUILD_FOLDER}\noarch\
          echo "cmd-4"
          echo "file:\\${BUILD_FOLDER}\noarch\"
          echo "cmd-5"
          echo %BUILD_FOLDER%
          echo "cmd-6"
          echo BUILD_FOLDER

      - name: Show variables for Windows-2
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER="%TEMP%\matchms\_build\"
          echo "cmd-7"
          echo $BUILD_FOLDER

      - name: Show variables for Windows-3
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER="%TEMP%\matchms\_build\"
          echo "cmd-8"
          echo file:\\$BUILD_FOLDER\noarch\

      - name: List folders for Windows-1
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER="%TEMP%\matchms\_build\"
          echo "cmd-1"
          ls -al "%TEMP%\matchms\_build"

      - name: List folders for Windows-2
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER="%TEMP%\matchms\_build\"
          echo "cmd-1"
          ls -al $BUILD_FOLDER
